#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT

#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define RETRO_TAPPING

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define RGBLIGHT_DEFAULT_HUE 195
