MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
# CONSOLE_ENABLE = yes # debug
RGBLIGHT_ENABLE = no 
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
NKRO_ENABLE = yes
TRI_LAYER_ENABLE = yes
# OLED_DRIVER = SSD1306

SRC += ./led.c

CONVERT_TO=promicro_rp2040
